name: cd

on:
  push:
  workflow_dispatch:
    
jobs:
  cd:
    name: CD
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Run Script
        run: mac/v4rb_mac_install_test.sh