name: valentina_install_test_mac

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
    
jobs:
  vpython_install_test_mac:
    name: vpython_install_test_mac
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Run Script
        run: mac/vpython_install_test_mac.sh ${{ github.event.inputs.version }}

  v4rb_install_test_mac:
    name: v4rb_install_test_mac
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Run Script
        run: mac/v4rb_mac_install_test.sh ${{ github.event.inputs.version }}

  vserver_install_test_mac:
    name: vserver_install_test_mac
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Run Script
        run: mac/vserver_mac_install_test.sh ${{ github.event.inputs.version }}