name: v4rb_install_test_linux

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
    
jobs:

  v4rb_install_test_linux_arm_32:
    name: v4rb_install_test_linux_arm_32
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and run ARM container
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm/v7 -t v4rb_arm32_test --load .
          docker run --rm v4rb_arm32_test ${{ github.event.inputs.version }}

  v4rb_install_test_linux_64:
    name: v4rb_install_test_linux_64
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Run Script
        run: linux/amd64/v4rb_install_test_linux_amd64.sh ${{ github.event.inputs.version }}